var nombreCurso='Node.Js';
var institucion='Comunidad IT';
var numeroAula=114;
var cantidadDeAlumnos=30;
var profesor='Nicolás Isnardi';
var horasSemanales=8;
var js=true;
var java=false;
var potencial;
var malaOnda=null;

console.log('Nombre de curso: '+ nombreCurso);
console.log('Dónde: '+ institucion);
console.log('Aula: '+ numeroAula);
console.log('Cantidad de alumnos: '+ cantidadDeAlumnos);
console.log('Profe: '+ profesor);
console.log('Horas semanales: '+ horasSemanales);
console.log('Lenguaje visto: JavaScript '+ js);
console.log('Lenguaje visto: Java '+java);
console.log('Aprendizajes extra: '+ potencial);
console.log('Mala onda: '+ malaOnda);

console.log('Nombre de curso: ', typeof nombreCurso);
console.log('Dónde: ', typeof institucion);
console.log('Aula: ', typeof numeroAula);
console.log('Cantidad de alumnos: ', typeof cantidadDeAlumnos);
console.log('Profe: ', typeof profesor);
console.log('Horas semanales: ', typeof horasSemanales);
console.log('Lenguaje visto: JavaScript ', typeof js);
console.log('Lenguaje visto: Java ', typeof java);
console.log('Aprendizajes extra: ', typeof potencial);
console.log('Mala onda: ', typeof malaOnda);
